# Generated by Django 4.1.5 on 2023-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abon", models.CharField(max_length=12, verbose_name="оператор")),
                ("code", models.CharField(max_length=24, verbose_name="код клиента")),
                (
                    "shortname",
                    models.CharField(max_length=24, verbose_name="короткое имя"),
                ),
                (
                    "fullname",
                    models.CharField(max_length=50, verbose_name="полное имя"),
                ),
            ],
            options={
                "unique_together": {
                    ("abon", "shortname"),
                    ("abon", "code"),
                    ("abon", "fullname"),
                },
            },
        ),
    ]
