# Generated by Django 4.1.5 on 2023-03-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="client",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="client",
            name="code",
            field=models.CharField(
                max_length=24, unique=True, verbose_name="код клиента"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="fullname",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="полное имя"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="shortname",
            field=models.CharField(
                max_length=24, unique=True, verbose_name="короткое имя"
            ),
        ),
        migrations.RemoveField(
            model_name="client",
            name="abon",
        ),
    ]
