# Generated by Django 4.1.5 on 2023-03-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tlg", "0002_alter_tlg_options"),
        ("reestr", "0004_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_records",
                to="reestr.client",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="tlg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tlg_records",
                to="tlg.tlg",
            ),
        ),
    ]
