# Generated by Django 4.1.5 on 2023-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0006_alter_record_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reestr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("abon", models.CharField(max_length=12)),
                ("date", models.DateField()),
                ("date_created", models.DateField()),
                ("fl_created", models.BooleanField(default=False)),
                ("fl_processed", models.BooleanField(default=False)),
                ("operator", models.CharField(max_length=20)),
                (
                    "records",
                    models.ManyToManyField(related_name="reestrs", to="reestr.record"),
                ),
            ],
        ),
    ]
