# Generated by Django 4.1.5 on 2023-03-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reestr", "0007_reestr"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTlg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_prefix",
                    models.TextField(
                        blank=True, max_length=12, verbose_name="префикс тлг-индекса"
                    ),
                ),
                (
                    "billing_bool",
                    models.BooleanField(
                        default=False, verbose_name="доступ к биллингу"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="полное имя"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
