# Generated by Django 4.1.5 on 2023-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0008_usertlg"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertlg",
            options={"verbose_name_plural": "Пользователи БД тлг-реестра"},
        ),
        migrations.AlterField(
            model_name="usertlg",
            name="fullname",
            field=models.CharField(max_length=30, verbose_name="полное имя"),
        ),
    ]
