# Generated by Django 4.1.5 on 2023-03-03 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reestr", "0009_alter_usertlg_options_alter_usertlg_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertlg",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="полное имя"
            ),
        ),
        migrations.AlterField(
            model_name="usertlg",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
