# Generated by Django 4.1.5 on 2023-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0010_alter_usertlg_fullname_alter_usertlg_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertlg",
            name="reestr_bool",
            field=models.BooleanField(
                default=True, verbose_name="доступ к формированию реестра"
            ),
        ),
    ]
