# Generated by Django 4.1.5 on 2023-03-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0011_usertlg_reestr_bool"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertlg",
            options={"verbose_name_plural": "Операторы связи/биллинга"},
        ),
    ]
