# Generated by Django 4.1.5 on 2023-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0012_alter_usertlg_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"verbose_name_plural": "Протарифицированные телеграммы"},
        ),
        migrations.AlterModelOptions(
            name="reestr",
            options={"verbose_name_plural": "Реестры"},
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="abon",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="operator",
        ),
        migrations.AddField(
            model_name="reestr",
            name="signature",
            field=models.CharField(
                default="", max_length=20, verbose_name="фамилия оператора"
            ),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="date",
            field=models.DateField(verbose_name="дата реестра"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="date_created",
            field=models.DateField(verbose_name="дата формирования реестра"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="fl_created",
            field=models.BooleanField(default=False, verbose_name="реестр сформирован"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="fl_processed",
            field=models.BooleanField(default=False, verbose_name="счет выставлен"),
        ),
        migrations.AlterField(
            model_name="reestr",
            name="number",
            field=models.IntegerField(verbose_name="порядковый номер за месяц"),
        ),
    ]
