# Generated by Django 4.1.5 on 2023-03-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0013_alter_record_options_alter_reestr_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reestr",
            name="usertlg",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reestrs",
                to="reestr.usertlg",
            ),
            preserve_default=False,
        ),
    ]
