# Generated by Django 4.1.5 on 2023-03-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0014_reestr_usertlg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reestr",
            name="records",
        ),
        migrations.RemoveField(
            model_name="reestr",
            name="usertlg",
        ),
        migrations.DeleteModel(
            name="Record",
        ),
        migrations.DeleteModel(
            name="Reestr",
        ),
    ]
