# Generated by Django 4.1.5 on 2023-03-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0015_remove_reestr_records_remove_reestr_usertlg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reestr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(verbose_name="порядковый номер за месяц"),
                ),
                ("date", models.DateField(verbose_name="дата реестра")),
                (
                    "date_created",
                    models.DateField(verbose_name="дата формирования реестра"),
                ),
                (
                    "fl_created",
                    models.BooleanField(
                        default=False, verbose_name="реестр сформирован"
                    ),
                ),
                (
                    "fl_processed",
                    models.BooleanField(default=False, verbose_name="счет выставлен"),
                ),
                (
                    "signature",
                    models.CharField(
                        default="", max_length=20, verbose_name="фамилия оператора"
                    ),
                ),
                (
                    "usertlg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reestrs",
                        to="reestr.usertlg",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Реестры",
            },
        ),
    ]
