# Generated by Django 4.1.5 on 2023-03-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tlg", "0002_alter_tlg_options"),
        ("reestr", "0016_reestr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autocost_bool", models.BooleanField(default=True)),
                (
                    "typeUrg",
                    models.CharField(
                        choices=[
                            ("O", "простая"),
                            ("U", "срочная"),
                            ("P", "почтой заказная"),
                            ("B", "до востребования"),
                        ],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "typeNot",
                    models.CharField(
                        choices=[
                            ("NN", "---"),
                            ("ON", "уведомление телеграфом"),
                            ("UN", "уведомление телеграфом срочное"),
                        ],
                        default="NN",
                        max_length=2,
                    ),
                ),
                (
                    "typeLX",
                    models.CharField(
                        choices=[
                            ("NL", "---"),
                            ("LX", "люкс/делюкс"),
                            ("LV", "люкс/в"),
                        ],
                        default="NL",
                        max_length=2,
                    ),
                ),
                ("todate_bool", models.BooleanField(default=False)),
                ("kkv_bool", models.BooleanField(default=False)),
                ("num_word", models.IntegerField(default=0)),
                ("cost_service", models.FloatField(default=0)),
                ("cost_todate", models.FloatField(default=0)),
                ("cost_lux", models.FloatField(default=0)),
                ("cost_notif", models.FloatField(default=0)),
                ("cost_deliv", models.FloatField(default=0)),
                ("cost_word", models.FloatField(default=0)),
                ("cost", models.FloatField(default=0)),
                ("cost_nds", models.FloatField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_records",
                        to="reestr.client",
                    ),
                ),
                (
                    "reestr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reestr_records",
                        to="reestr.reestr",
                    ),
                ),
                (
                    "tlg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tlg_records",
                        to="tlg.tlg",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Протарифицированные телеграммы",
            },
        ),
    ]
