# Generated by Django 4.1.5 on 2023-03-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tlgtarif", "0005_alter_tlgtarifcountry_country_and_more"),
        ("reestr", "0017_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="country_records",
                to="tlgtarif.country",
            ),
        ),
    ]
