# Generated by Django 4.1.5 on 2023-03-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0019_client_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reestr",
            name="number",
        ),
    ]
