# Generated by Django 4.1.5 on 2023-03-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0020_remove_reestr_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="cost_word",
            field=models.FloatField(
                default=0, verbose_name="Передача внутренней телеграммы, за слово"
            ),
        ),
    ]
