# Generated by Django 4.1.5 on 2023-03-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0021_alter_record_cost_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="cost_deliv",
            field=models.FloatField(default=0, verbose_name="Доставка телеграммы"),
        ),
        migrations.AlterField(
            model_name="record",
            name="cost_word",
            field=models.FloatField(
                default=0, verbose_name="Передача телеграммы, за слово"
            ),
        ),
    ]
