# Generated by Django 4.1.5 on 2023-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0022_alter_record_cost_deliv_alter_record_cost_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="cost_notif",
            field=models.FloatField(
                default=0, verbose_name="Уведомление о вручении телеграфом"
            ),
        ),
    ]
