# Generated by Django 4.1.5 on 2023-03-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0023_alter_record_cost_notif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="cost_lux",
            field=models.FloatField(default=0, verbose_name="Художественный бланк"),
        ),
    ]
