# Generated by Django 4.1.5 on 2023-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reestr", "0024_alter_record_cost_lux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="cost_todate",
            field=models.FloatField(
                default=0,
                verbose_name="Доставка телеграммы в срок, указанный отправителем",
            ),
        ),
    ]
