# Generated by Django 4.1.5 on 2023-02-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_country", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="TlgTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_begin", models.DateTimeField(verbose_name="начало действия")),
                ("date_end", models.DateTimeField(verbose_name="окончание действия")),
                (
                    "delivery_ordinary",
                    models.FloatField(default=0, verbose_name="простая"),
                ),
                (
                    "delivery_urgent",
                    models.FloatField(default=0, verbose_name="СРОЧНАЯ"),
                ),
                (
                    "delivery_post",
                    models.FloatField(default=0, verbose_name="ПОЧТОЙ ЗАКАЗНОЕ"),
                ),
                (
                    "delivery_box",
                    models.FloatField(default=0, verbose_name="ДО ВОСТРЕБОВАНИЯ"),
                ),
                ("word_ordinary", models.FloatField(default=0, verbose_name="простая")),
                ("word_urgent", models.FloatField(default=0, verbose_name="СРОЧНАЯ")),
                (
                    "notification_ordinary",
                    models.FloatField(default=0, verbose_name="УВЕДОМЛЕНИЕ ТЕЛЕГРАФОМ"),
                ),
                (
                    "notification_urgent",
                    models.FloatField(
                        default=0, verbose_name="УВЕДОМЛЕНИЕ ТЕЛЕГРАФОМ СРОЧНОЕ"
                    ),
                ),
                (
                    "lux_ordinary",
                    models.FloatField(default=0, verbose_name="ЛЮКС / ДЕЛЮКС"),
                ),
                ("lux_visual", models.FloatField(default=0, verbose_name="ЛЮКС/В")),
                ("todate", models.FloatField(default=0, verbose_name="ВРУЧИТЬ")),
                ("nds_percent", models.FloatField(default=0, verbose_name="НДС")),
            ],
        ),
        migrations.CreateModel(
            name="TlgTarifCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_begin", models.DateTimeField(verbose_name="начало действия")),
                ("date_end", models.DateTimeField(verbose_name="окончание действия")),
                ("word_ordinary", models.FloatField(default=0, verbose_name="простая")),
                ("word_urgent", models.FloatField(default=0, verbose_name="СРОЧНАЯ")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tlgtarif.country",
                    ),
                ),
            ],
        ),
    ]
