# Generated by Django 4.1.5 on 2023-02-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tlgtarif", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="delivery_box_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="delivery_post_bool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="lux_ordinary_bool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="lux_visual_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="notification_ordinary_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="notification_urgent_bool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="country",
            name="todate_bool",
            field=models.BooleanField(default=True),
        ),
    ]
