# Generated by Django 4.1.5 on 2023-02-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tlgtarif", "0003_alter_country_delivery_box_bool_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Страны экс-СССР"},
        ),
        migrations.AlterModelOptions(
            name="tlgtarif",
            options={"verbose_name_plural": "Тарифы, Россия"},
        ),
        migrations.AlterModelOptions(
            name="tlgtarifcountry",
            options={"verbose_name_plural": "Тарифы, экс-СССР"},
        ),
    ]
