# Generated by Django 4.1.5 on 2023-03-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tlgtarif", "0004_alter_country_options_alter_tlgtarif_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tlgtarifcountry",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tlgtarif.country",
                verbose_name="страна",
            ),
        ),
        migrations.AlterField(
            model_name="tlgtarifcountry",
            name="word_urgent",
            field=models.FloatField(default=0, verbose_name="срочная"),
        ),
    ]
