# Generated by Django 4.1.5 on 2023-02-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tlg", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tlg",
            options={"verbose_name_plural": "Телеграммы"},
        ),
    ]
